# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sendFile_pb2 as sendFile__pb2


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.upload = channel.stream_unary(
                '/uploadFile.FileService/upload',
                request_serializer=sendFile__pb2.Chunk.SerializeToString,
                response_deserializer=sendFile__pb2.UploadStatus.FromString,
                )
        self.sendTask = channel.unary_stream(
                '/uploadFile.FileService/sendTask',
                request_serializer=sendFile__pb2.Task.SerializeToString,
                response_deserializer=sendFile__pb2.NewChunk.FromString,
                )
        self.bidupload = channel.stream_stream(
                '/uploadFile.FileService/bidupload',
                request_serializer=sendFile__pb2.Chunk.SerializeToString,
                response_deserializer=sendFile__pb2.NewChunk.FromString,
                )


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bidupload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'upload': grpc.stream_unary_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=sendFile__pb2.Chunk.FromString,
                    response_serializer=sendFile__pb2.UploadStatus.SerializeToString,
            ),
            'sendTask': grpc.unary_stream_rpc_method_handler(
                    servicer.sendTask,
                    request_deserializer=sendFile__pb2.Task.FromString,
                    response_serializer=sendFile__pb2.NewChunk.SerializeToString,
            ),
            'bidupload': grpc.stream_stream_rpc_method_handler(
                    servicer.bidupload,
                    request_deserializer=sendFile__pb2.Chunk.FromString,
                    response_serializer=sendFile__pb2.NewChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uploadFile.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/uploadFile.FileService/upload',
            sendFile__pb2.Chunk.SerializeToString,
            sendFile__pb2.UploadStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/uploadFile.FileService/sendTask',
            sendFile__pb2.Task.SerializeToString,
            sendFile__pb2.NewChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def bidupload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/uploadFile.FileService/bidupload',
            sendFile__pb2.Chunk.SerializeToString,
            sendFile__pb2.NewChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
